---
title: "kimSound_analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(dplyr)
library(plyr)
library(ggplot2)
library(cowplot)
library(ggpubr)
library(rstatix)
library(effsize)
library(psych)
```

```{r}
# custom functions

# dupe MATLAB's smooth function with window = 5
smooth <- function(y ){
  h <- c(head(y, 1), mean(head(y, 3), na.rm=T))
  t <- c(mean(tail(y, 3), na.rm=T), tail(y, 1))
  m <- c()
  for (i in 3:(length(y)-2)) {
    m <- c(m, mean(y[i-2:i+2], na.rm=T))
  }
  c(h, m, t)
}


unpairedTAndCohensD <- function(dataA, dataB) {
  testout = t.test(dataA, dataB, paired = FALSE, var.equal = TRUE) # use Student's t-test
  t = testout$statistic
  df = testout$parameter
  p = testout$p.value
  
  testout = effsize::cohen.d(dataA, dataB, paired = FALSE)
  d = testout$estimate
  return(c(t, df, p, d))
}
```


```{r}
# load data
ste = read.csv("C:/Users/olivia/Documents/GitHub/TaskSuccessRewardImplicitAdapt/data_fig3_soundtargetsize.csv")
ste$target = as.factor(ste$targAngle)
ste$sub = as.factor(ste$subject)
#comment this line if you don't want to use maxvelAngle
ste$epAngle = ste$reachAngle
ste$reachAngle = ste$maxvelAngle
```

```{r}
# initial preprocessing -- remove outliers, baseline subtraction

# find and remove outliers
targAngles = unique(ste$target)
numBadTrials = vector()
tgt_SDs = data.frame(matrix(NA, length(unique(ste$sub)), length(targAngles)))
badTrialRows = c() # need to keep list of bad trials for later
for (s in unique(ste$sub)) {
  badTrialCounter = 0
  t = 0
  for(targ in targAngles){
    t = t+1
    thisdata = subset(ste, sub==s & target==targ)
    smoothed_hand = smooth(thisdata$reachAngle)
    detrended = thisdata$reachAngle - smoothed_hand
    tgt_SDs[s,t] = sd(detrended, na.rm = T)
    for (i in 1:length(detrended)) {
      if (!is.na(thisdata$reachAngle[i])) {
        if ((abs(detrended[i]) > 3*tgt_SDs[s,t]) | (abs(thisdata$reachAngle[i]) > 90)) {
          badTrialRows = c(badTrialRows, rownames(thisdata)[i]) # log original df index for later
          badTrialCounter = badTrialCounter + 1 # update bad trial counter
        }
      }
    }
  }
  numBadTrials[s] = badTrialCounter
}
ste$reachAngle_raw = ste$reachAngle # preserve raw reach angles
for (val in badTrialRows) {
  ste$reachAngle[as.numeric(val)] = NA # replace excluded values with NA
  ste$epAngle[as.numeric(val)] = NA # replace excluded values with NA
}

ste.base = subset(ste, trialNum > 40 & trialNum<121) # baseline trials with feedback

#subtract baseline biases for each participant (targetwise)
targAngles = unique(ste$target)
for(targ in targAngles){
  ste_targ.base = subset(ste.base, targAngle == targ)
  ste.sub_targ_bias = tapply(ste_targ.base$reachAngle, ste_targ.base$sub, mean, na.rm = T)
  
  for(s in unique(ste$subject)){
    ste$reachAngle[ste$subject == s & ste$targAngle == targ] = ste$reachAngle[ste$subject == s & ste$targAngle == targ] - ste.sub_targ_bias[s]
  }
}

```

```{r}
# subset data
ste$bin = as.factor(ste$bin)
hit_knock = subset(ste, condition == 1)
hit_ding = subset(ste, condition == 2)
miss_knock = subset(ste, condition == 3)
miss_ding = subset(ste, condition == 4)
```

```{r}
#binned learning curve
binSubjectData <- function(dfin){
  sub = c()
  bin = c()
  reachAngle = c()
  for (s in unique(dfin$sub)){
    tempdata = subset(dfin, sub==s)
    binneddata = tapply(tempdata$reachAngle, tempdata$bin, mean, na.rm=T)
    for (b in 1:length(binneddata)) {
      sub = c(sub, s)
      bin = c(bin, as.numeric(rownames(binneddata)[b]))
      reachAngle = c(reachAngle, binneddata[b])
    }
  }
  subjectwiseBins = data.frame(sub, bin, reachAngle)
  return(subjectwiseBins)
}

hit_knock_binned = binSubjectData(hit_knock)
hit_knock_bin_lc = tapply(hit_knock_binned$reachAngle, hit_knock_binned$bin, mean, na.rm = T)
hit_knock_bin_lc_ci = tapply(hit_knock_binned$reachAngle, hit_knock_binned$bin, sd, na.rm = T) /sqrt(length(unique(hit_knock_binned$sub)))

hit_ding_binned = binSubjectData(hit_ding)
hit_ding_bin_lc = tapply(hit_ding_binned$reachAngle, hit_ding_binned$bin, median, na.rm = T)
hit_ding_bin_lc_ci = tapply(hit_ding_binned$reachAngle, hit_ding_binned$bin, sd, na.rm = T) /sqrt(length(unique(hit_ding_binned$sub)))

miss_knock_binned = binSubjectData(miss_knock)
miss_knock_bin_lc = tapply(miss_knock_binned$reachAngle, miss_knock_binned$bin, mean, na.rm = T)
miss_knock_bin_lc_ci = tapply(miss_knock_binned$reachAngle, miss_knock_binned$bin, sd, na.rm = T) /sqrt(length(unique(miss_knock$sub)))

miss_ding_binned = binSubjectData(miss_ding)
miss_ding_bin_lc = tapply(miss_ding_binned$reachAngle, miss_ding_binned$bin, mean, na.rm = T)
miss_ding_bin_lc_ci = tapply(miss_ding_binned$reachAngle, miss_ding_binned$bin, sd, na.rm = T) /sqrt(length(unique(miss_ding_binned$sub)))


theme_set(theme_cowplot())
custom_palette = c("#A6CEE3","#1F78B4", "#FB9A99", "#E31A1C")


binned_lcs = data.frame(
  condition = factor(c(rep("Miss Knock", 110), rep("Miss Ding", 110), 
                       rep("Hit Knock", 110), rep("Hit Ding", 110))),
  trial = c(1:110-0.6, 1:110-0.3, 1:110+0.3, 1:110+0.6),
  epAngle = c(miss_knock_bin_lc, miss_ding_bin_lc, hit_knock_bin_lc, hit_ding_bin_lc),
  sd = c(miss_knock_bin_lc_ci, miss_ding_bin_lc_ci, hit_knock_bin_lc_ci, hit_ding_bin_lc_ci)
)
plot_lcs = ggplot(data = binned_lcs, aes(x = trial, y=epAngle, group=condition, color= condition)) + 
  geom_point() + 
  geom_vline(xintercept = 15.5, linetype = "dashed") + 
  geom_vline(xintercept = 95.5, linetype = "dashed") + 
  geom_ribbon(aes(x = trial, ymin = epAngle - sd, ymax = epAngle + sd, fill = condition), inherit.aes = F)+
  scale_color_manual(values = custom_palette) +
  scale_fill_manual(values = custom_palette) +
  ylab("Hand Angle \n(degrees)") +
  xlab("Cycle (8 trials)")
plot_lcs

# save data that went into the figure
learningCurveDF = data.frame(miss_knock_bin_lc, miss_knock_bin_lc_ci,
                             miss_ding_bin_lc, miss_ding_bin_lc_ci,
                             hit_knock_bin_lc, hit_knock_bin_lc_ci,
                             hit_ding_bin_lc, hit_ding_bin_lc_ci)
write.csv(learningCurveDF,"C:/Users/olivia/Documents/GitHub/TaskSuccessRewardImplicitAdapt/output_fig3_binnedLC_meanSEM.csv", row.names = FALSE)
```


```{r}
## early learning rates
getEarlyLR <- function(dfin) {
  # this approach is what Kim et al., 2019 did
  output = vector()
  for (s in unique(dfin$sub)) {
    tempvals = subset(dfin[dfin$sub==s,], bin < 23 & bin > 17)
    lastbin = tapply(tempvals$reachAngle, tempvals$bin, mean, na.rm = T)
    output[s] = mean(lastbin)/5
  }
  return(output)
}

miss_knock_early_lr = getEarlyLR(miss_knock_binned)
miss_ding_early_lr = getEarlyLR(miss_ding_binned)
hit_knock_early_lr = getEarlyLR(hit_knock_binned)
hit_ding_early_lr = getEarlyLR(hit_ding_binned)

# arrange into dataframe for 2 way ANOVA
sub = 1:96
targetSize = c(rep("Small", 48), rep("Big", 48))
sound = c(rep("knock", 24), rep("ding", 24), rep("knock", 24), rep("ding", 24))
earlyLR = c(miss_knock_early_lr, miss_ding_early_lr,
              hit_knock_early_lr, hit_ding_early_lr)
earlyLRDF = data.frame(sub, targetSize, sound, earlyLR)
earlyLRDF$targetSize = as.factor(earlyLRDF$targetSize)
earlyLRDF$sound = as.factor(earlyLRDF$sound)
# ggboxplot(earlyLRDF, x = "targetSize", y = "earlyLR", color = "sound",
#           palette = c("#00AFBB", "#E7B800")) # boxplot early learning rate ("earlyLR") by task success groups ("targetSize"). color box plots by the second grouping factor of the sound played ("sound")

earlyLR.aov2Way <- anova_test(
  data = earlyLRDF,
  formula = earlyLR ~ targetSize + sound + targetSize*sound,
  dv = earlyLR)
get_anova_table(earlyLR.aov2Way) 


early_lr = data.frame(
  condition = c(rep("Miss\nKnock", 24), rep("Miss\nDing", 24), 
                rep("Hit\nKnock", 24), rep("Hit\nDing", 24)),
  lr = c(as.numeric(miss_knock_early_lr), as.numeric(miss_ding_early_lr), as.numeric(hit_knock_early_lr), as.numeric(hit_ding_early_lr))
)
early_lr_smry = ddply(early_lr, .(condition), summarise,
                      early_mean = mean(lr, na.rm = T),
                      early_se = sd(lr, na.rm = T)/sqrt(24))

plot_lr = ggplot() +  geom_point(data=early_lr_smry, aes(y=early_mean, x=condition, color = condition), size = 3) + geom_errorbar(data=early_lr_smry, aes(y=early_mean, x=condition, ymin = early_mean - early_se,ymax = early_mean + early_se, color = condition), size = 1,  width = 0) + #geom_boxplot(data=early_lr, aes(y=lr, x=condition, color = condition), outlier.shape=NA) +
  scale_color_manual(values = custom_palette) +
  scale_fill_manual(values = custom_palette) +
  ylab("Learning Rate \n(degrees/bin)") +
  xlab("Condition") +
  ylim(0.25, 2)+
  theme(legend.position="none")

plot_lr

# plot_lr = ggplot(data=early_lr, aes(y=lr, x=condition, color = condition)) + 
#   stat_summary(fun.data=MinMeanSEMMax, geom="boxplot")+
#   scale_color_manual(values = custom_palette) +
#   scale_fill_manual(values = custom_palette) +
#   ylab("Learning Rate \n(degrees/bin)") +
#   xlab("Condition") +
#   ylim(0, 1.25)+
#   theme(legend.position="none")
# 
# plot_lr

write.csv(early_lr_smry,"C:/Users/olivia/Documents/GitHub/TaskSuccessRewardImplicitAdapt/output_fig3_earlyLR_meanSEM.csv", row.names = TRUE)
```

```{r}

##late asymptotes (clamp 1)
miss_knock.late1 = subset(miss_knock_binned, bin>85 & bin<96)
hit_knock.late1 = subset(hit_knock_binned, bin>85 & bin<96)
miss_knock_late1_asym = tapply(miss_knock.late1$reachAngle, miss_knock.late1$sub, mean, na.rm = T)
hit_knock_late1_asym = tapply(hit_knock.late1$reachAngle, hit_knock.late1$sub, mean, na.rm = T)
miss_ding.late1 = subset(miss_ding_binned, bin>85 & bin<96)
hit_ding.late1 = subset(hit_ding_binned, bin>85 & bin<96)
miss_ding_late1_asym = tapply(miss_ding.late1$reachAngle, miss_ding.late1$sub, mean, na.rm = T)
hit_ding_late1_asym = tapply(hit_ding.late1$reachAngle, hit_ding.late1$sub, mean, na.rm = T)

# arrange into dataframe for 2 way ANOVA
asym1 = c(miss_knock_late1_asym, miss_ding_late1_asym,
              hit_knock_late1_asym, hit_ding_late1_asym)
asym1DF = data.frame(sub, targetSize, sound, asym1)
asym1DF$targetSize = as.factor(asym1DF$targetSize)
asym1DF$sound = as.factor(asym1DF$sound)
# ggboxplot(asym1DF, x = "targetSize", y = "asym1", color = "sound",
#           palette = c("#00AFBB", "#E7B800")) # boxplot initial asymptote ("asym1") by task success groups ("targetSize"). color box plots by the second grouping factor of the sound played ("sound")


asym1.aov2Way <- anova_test(
  data = asym1DF,
  formula = asym1 ~ targetSize + sound + targetSize*sound,
  dv = asym1)
get_anova_table(asym1.aov2Way) 


#asym figures
asymptotes = data.frame(
  condition = c(rep("Miss\nKnock", 24), rep("Miss\nDing", 24), 
                rep("Hit\nKnock", 24), rep("Hit\nDing", 24)),
  asym = c(as.numeric(miss_knock_late1_asym), as.numeric(miss_ding_late1_asym), as.numeric(hit_knock_late1_asym), as.numeric(hit_ding_late1_asym))
)
asym_smry = ddply(asymptotes, .(condition), summarise,
                        asym_mean = mean(asym),
                        asym_se = sd(asym)/sqrt(24))

plot_asym = ggplot() +  geom_point(data=asym_smry, aes(y=asym_mean, x=condition, color = condition), size = 3) +  geom_errorbar(data=asym_smry, aes(y=asym_mean, x=condition, ymin = asym_mean - asym_se,ymax = asym_mean + asym_se, color = condition), size = 1, width = 0) + #  geom_boxplot(data=asymptotes, aes(y=asym, x=condition, color = condition), outlier.shape=NA) +
  scale_color_manual(values = custom_palette) +
  scale_fill_manual(values = custom_palette) +
  ylab("Asymptote \n(degrees)") +
  xlab("Condition") +
  ylim(0,25)+
  theme(legend.position="none")
plot_asym

write.csv(asym_smry,"C:/Users/olivia/Documents/GitHub/TaskSuccessRewardImplicitAdapt/output_fig3_asym1_meanSEM.csv", row.names = TRUE)
```


```{r}
#washout
getPctRet <- function(dfin) {
  # retention as % retained at end of 5 no-FB cycles
  wash = subset(dfin, bin == 100)
  lastcycle = subset(dfin, bin == 95)
  output = tapply(wash$reachAngle, wash$sub, mean, na.rm = T)/
    tapply(lastcycle$reachAngle, wash$sub, mean, na.rm = T)
  return(output)
}

miss_knock_wash = getPctRet(miss_knock_binned)
hit_knock_wash = getPctRet(hit_knock_binned)
miss_ding_wash = getPctRet(miss_ding_binned)
hit_ding_wash = getPctRet(hit_ding_binned)

# put into DF for ANOVA
washRet = c(miss_knock_wash, miss_ding_wash,
              hit_knock_wash, hit_ding_wash)
washRetDF = data.frame(sub, targetSize, sound, washRet)
washRetDF$targetSize = as.factor(washRetDF$targetSize)
washRetDF$sound = as.factor(washRetDF$sound)
# ggboxplot(washRetDF, x = "targetSize", y = "washRet", color = "sound",
#           palette = c("#00AFBB", "#E7B800")) # boxplot retention ("washRet") by task success groups ("targetSize"). color box plots by the second grouping factor of the sound played ("sound")


washRet.aov2Way <- anova_test(
  data = washRetDF,
  formula = washRet ~ targetSize + sound + targetSize*sound,
  dv = washRet)
get_anova_table(washRet.aov2Way) 


statlist = unpairedTAndCohensD(washRetDF$washRet[washRetDF$sound == 'knock'],
                               washRetDF$washRet[washRetDF$sound == 'ding']) # returns t, df, p, and cohen's d


washout = data.frame(
  condition = c(rep("Miss\nKnock", 24), rep("Miss\nDing", 24), 
                rep("Hit\nKnock", 24), rep("Hit\nDing", 24)),
  wash = c(as.numeric(miss_knock_wash), as.numeric(miss_ding_wash), as.numeric(hit_knock_wash), as.numeric(hit_ding_wash))
)
wash_smry = ddply(washout, .(condition), summarise,
                        wash_mean = mean(wash),
                        wash_se = sd(wash)/sqrt(24))

plot_wash = ggplot() + geom_point(data=wash_smry, aes(y=wash_mean, x=condition, color = condition), size = 3) +geom_errorbar(data=wash_smry, aes(y=wash_mean, x=condition, ymin = wash_mean - wash_se,ymax = wash_mean + wash_se, color = condition), size = 1, width = 0) + #geom_boxplot(data=washout, aes(y=wash, x=condition, color = condition), outlier.shape=NA) +
  scale_color_manual(values = custom_palette) +
  scale_fill_manual(values = custom_palette) +
  ylab("Washout Retention (%)") +
  xlab("Condition") +
  ylim(0,1.1)+
  theme(legend.position="none")
plot_wash


write.csv(wash_smry,"C:/Users/olivia/Documents/GitHub/TaskSuccessRewardImplicitAdapt/output_fig3_wash_meanSEM.csv", row.names = TRUE)



washout = data.frame(
  condition = c(rep("Knock", 24), rep("Ding", 24), 
                rep("Knock", 24), rep("Ding", 24)),
  wash = c(as.numeric(miss_knock_wash), as.numeric(miss_ding_wash), as.numeric(hit_knock_wash), as.numeric(hit_ding_wash))
)
wash_smry = ddply(washout, .(condition), summarise,
                        wash_mean = mean(wash),
                        wash_se = sd(wash)/sqrt(48))

```


```{r}
# at baseline, is the magnitude of the change in hand angle influenced by the sound heard?
computeUpdatesInRange <- function(dfin, winstart, winstop) {
  output = subset(dfin, as.numeric(ste$bin)>= winstart & as.numeric(ste$bin)<= winstop)
  output$hits = as.factor(output$hits)
  rownames(output)<-NULL
  # compute update size (with update size being on this trial) -- recall that this must be done targetwise
  targAngles = unique(output$target)
  output$update = output$reachAngle # placeholder for now
  output$update[1:length(output$update)] = NA # clear values
  output$afterHit = output$reachAngle # placeholder
  output$afterHit = NA # clear values
  for (s in unique(output$sub)) {
    for(targ in targAngles){
      thisdata = subset(output, sub==s & target==targ)
      for (i in 1:(nrow(thisdata)-1)) {
        output$update[as.numeric(rownames(thisdata)[i])] =
          thisdata$reachAngle[i+1] - thisdata$reachAngle[i]
      }
      # this part may not be necessary
      for (i in 2:(nrow(thisdata))) {
        if (thisdata$hits[i-1] == 1) {
          output$afterHit[as.numeric(rownames(thisdata)[i])] = 1
        } else {
          output$afterHit[as.numeric(rownames(thisdata)[i])] = 0
        }
      }
    }
  }
  return(output)
}

# Need to restrict analysis to window where the sound feedback might differ --
# otherwise, there is just way more possible variability in hand angle built in
# to the trials where people hear the knock
getRespInRange <- function(dfin, soundCndn, tgtSizeCndn, winmin, winmax) {
  sub = c()
  sound = c()
  tgtSize = c()
  updateSize = c()
  responseVar = c()
  for (s in unique(dfin$sub)) {
    sub = c(sub, s)
    sound = c(sound, soundCndn)
    tgtSize = c(tgtSize, tgtSizeCndn)
    updateSize = c(updateSize, mean(abs(dfin$update[dfin$sub == s
                                           & abs(dfin$epAngle)<=winmax
                                           & abs(dfin$epAngle)>=winmin]), na.rm=T))
    responseVar = c(responseVar, sd(dfin$reachAngle[dfin$sub == s
                                           & abs(dfin$epAngle)<=winmax
                                           & abs(dfin$epAngle)>=winmin], na.rm=T))
  }
  outputDF = data.frame(sub, sound, tgtSize, updateSize, responseVar)
  return(outputDF)
}

getBinnedUpdateDF <- function(dfin) {
  hitKnock = subset(dfin, condition == 1) # knock big
  hitDing = subset(dfin, condition == 2) # ding big
  missKnock = subset(dfin, condition == 3) # knock small
  missDing = subset(dfin, condition == 4) # ding small
  # break down by all groups
  df1 = getRespInRange(missKnock, "knock", "small", 1.79057, 5.37345) # for this group, person will have heard knock and seen small target in the specified window
  df2 = getRespInRange(missDing, "ding", "small", 1.79057, 5.37345) # hear ding see small target in window
  df3 = getRespInRange(hitKnock, "knock", "big", 1.79057, 5.37345) # hear knock see big target in window
  df4 = getRespInRange(hitDing, "ding", "big", 1.79057, 5.37345) # hear ding see big target in window
  updates_bin = rbind(df1,df2,df3,df4)
  updates_bin$sound = as.factor(updates_bin$sound)
  updates_bin$tgtSize = as.factor(updates_bin$tgtSize)
  updates_bin$condition = paste(updates_bin$tgtSize, updates_bin$sound)
  return(updates_bin)
}

ste.baseNoFB = computeUpdatesInRange(ste, 1, 5)
updates_bin.baseNoFB = getBinnedUpdateDF(ste.baseNoFB)

# check for effects on size of update
#ggline(updates_bin.baseNoFB, x = "sound", y = "updateSize", color="tgtSize", add = c("mean_se"))
toneRespUpdate_baseNoFB.aov2Way <- anova_test(
  data = updates_bin.baseNoFB,
  formula = updateSize ~ sound + tgtSize + sound*tgtSize,
  dv = updateSize)
get_anova_table(toneRespUpdate_baseNoFB.aov2Way) # stlRwdTS.aov2Way$ges[1]
statlist = unpairedTAndCohensD(updates_bin.baseNoFB$updateSize[updates_bin.baseNoFB$sound == 'knock'],
                               updates_bin.baseNoFB$updateSize[updates_bin.baseNoFB$sound == 'ding'])
t = statlist[1]
df = statlist[2]
p = statlist[3]
d = statlist[4]

#ggline(updates_bin.baseNoFB, x = "sound", y = "updateSize", add = c("mean_se"))


noFBBL_smry = ddply(updates_bin.baseNoFB, .(condition), summarise,
                        update_mean = mean(updateSize),
                        update_se = sd(updateSize)/sqrt(24))

plot_noFBBLToneSens = ggplot() +
  geom_point(data=noFBBL_smry, aes(y=update_mean, x=condition, color = condition), size = 3) +
  geom_errorbar(data=noFBBL_smry, aes(y=update_mean, x=condition, ymin = update_mean - update_se,
                                    ymax = update_mean + update_se, color = condition), size = 1, width = 0) + #geom_boxplot(data=washout, aes(y=wash, x=condition, color = condition), outlier.shape=NA) +
  scale_color_manual(values = custom_palette) +
  scale_fill_manual(values = custom_palette) +
  ylab("Update Size (deg)") +
  xlab("Condition") +
  ylim(2.5, 5.5)+
  theme(legend.position="none")
plot_noFBBLToneSens

write.csv(noFBBL_smry,"C:/Users/olivia/Documents/GitHub/TaskSuccessRewardImplicitAdapt/output_fig3_noFBBLToneSens_meanSEM.csv", row.names = TRUE)

# smaller panel inset for stats
noFBBL_sound_smry = ddply(updates_bin.baseNoFB, .(sound), summarise,
                        update_mean = mean(updateSize),
                        update_se = sd(updateSize)/sqrt(48))

plot_noFBBLToneSens_sound = ggplot() +
  geom_point(data=noFBBL_sound_smry, aes(y=update_mean, x=sound), size = 3) +
  geom_errorbar(data=noFBBL_sound_smry, aes(y=update_mean, x=sound, ymin = update_mean - update_se,
                                    ymax = update_mean + update_se), size = 1, width = 0) + #geom_boxplot(data=washout, aes(y=wash, x=condition, color = condition), outlier.shape=NA) +
  scale_color_manual(values = custom_palette) +
  scale_fill_manual(values = custom_palette) +
  ylab("Update Size (deg)") +
  xlab("Condition") +
  ylim(2.5, 5.5)+
  theme(legend.position="none")
plot_noFBBLToneSens_sound

write.csv(noFBBL_sound_smry,"C:/Users/olivia/Documents/GitHub/TaskSuccessRewardImplicitAdapt/output_fig3_noFBBLToneSens_sound_meanSEM.csv", row.names = TRUE)

```

```{r}
# now check with FB
ste.baseFB = computeUpdatesInRange(ste, 6, 15)
updates_bin.baseFB = getBinnedUpdateDF(ste.baseFB)

# check for effects on size of update
#ggline(updates_bin.baseFB, x = "sound", y = "updateSize", color="tgtSize", add = c("mean_se"))
toneRespUpdate_baseFB.aov2Way <- anova_test(
  data = updates_bin.baseFB,
  formula = updateSize ~ sound + tgtSize + sound*tgtSize,
  dv = updateSize)
get_anova_table(toneRespUpdate_baseFB.aov2Way) # stlRwdTS.aov2Way$ges[1]

statlist = unpairedTAndCohensD(updates_bin.baseFB$updateSize[updates_bin.baseFB$tgtSize == 'small'],
                               updates_bin.baseFB$updateSize[updates_bin.baseFB$tgtSize == 'big'])
t = statlist[1]
df = statlist[2]
p = statlist[3]
d = statlist[4]

#ggline(updates_bin.baseFB, x = "tgtSize", y = "updateSize", add = c("mean_se"))



FBBL_smry = ddply(updates_bin.baseFB, .(condition), summarise,
                        update_mean = mean(updateSize),
                        update_se = sd(updateSize)/sqrt(24))

plot_FBBLToneSens = ggplot() +
  geom_point(data=FBBL_smry, aes(y=update_mean, x=condition, color = condition), size = 3) +
  geom_errorbar(data=FBBL_smry, aes(y=update_mean, x=condition, ymin = update_mean - update_se,
                                    ymax = update_mean + update_se, color = condition), size = 1, width = 0) + #geom_boxplot(data=washout, aes(y=wash, x=condition, color = condition), outlier.shape=NA) +
  scale_color_manual(values = custom_palette) +
  scale_fill_manual(values = custom_palette) +
  ylab("Update Size (deg)") +
  xlab("Condition") +
  ylim(2.5, 5.5)+
  theme(legend.position="none")
plot_FBBLToneSens

write.csv(FBBL_smry,"C:/Users/olivia/Documents/GitHub/TaskSuccessRewardImplicitAdapt/outpuf_fig3_FBBLToneSens_meanSEM.csv", row.names = TRUE)

# smaller panel inset for stats
FBBL_tgtSize_smry = ddply(updates_bin.baseFB, .(tgtSize), summarise,
                        update_mean = mean(updateSize),
                        update_se = sd(updateSize)/sqrt(48))

plot_FBBLToneSens_tgtSize = ggplot() +
  geom_point(data=FBBL_tgtSize_smry, aes(y=update_mean, x=tgtSize), size = 3) +
  geom_errorbar(data=FBBL_tgtSize_smry, aes(y=update_mean, x=tgtSize, ymin = update_mean - update_se,
                                    ymax = update_mean + update_se), size = 1, width = 0) + #geom_boxplot(data=washout, aes(y=wash, x=condition, color = condition), outlier.shape=NA) +
  scale_color_manual(values = custom_palette) +
  scale_fill_manual(values = custom_palette) +
  ylab("Update Size (deg)") +
  xlab("Condition") +
  ylim(2.5, 5.5)+
  theme(legend.position="none")
plot_FBBLToneSens_tgtSize

write.csv(FBBL_tgtSize_smry,"C:/Users/olivia/Documents/GitHub/TaskSuccessRewardImplicitAdapt/output_fig3_FBBLToneSens_tgtSize_meanSEM.csv", row.names = TRUE)
```

```{r}
ggarrange(plot_lcs,
          ggarrange(plot_noFBBLToneSens, plot_FBBLToneSens, plot_lr, plot_asym, plot_wash, ncol=5, legend=NULL),
          nrow = 2, common.legend = T)
```