---
title: "analysis_fig4_tsayrep"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(dplyr)
library(plyr)
library(ggplot2)
library(cowplot)
library(ggpubr)
library(rstatix)
library(effsize)
```

```{r}
# User-specific TODO
setwd('C:/Users/kimol/Documents/GitHub/RewardTaskSuccess') # TODO: go to appropriate working directory
```

```{r}
# custom functions

# dupe MATLAB's smooth function with window = 5
smooth <- function(y ){
  h <- c(head(y, 1), mean(head(y, 3), na.rm=T))
  t <- c(mean(tail(y, 3), na.rm=T), tail(y, 1))
  m <- c()
  for (i in 3:(length(y)-2)) {
    m <- c(m, mean(y[i-2:i+2], na.rm=T))
  }
  c(h, m, t)
}

pairedTAndCohensD <- function(dataA, dataB) {
  testout = t.test(dataA, dataB, paired = TRUE, var.equal=TRUE) # use Student's t-test
  t = testout$statistic
  df = testout$parameter
  p = testout$p.value
  
  testout = cohen.d(dataA, dataB, paired = TRUE)
  d = testout$estimate
  return(c(t, df, p, d))
}

```


```{r}
# load data
kr = read.csv("data_fig4_tsayrep.csv")
kr = kr[kr$TrialNum>103,] # omit data in 

# interpret Target Jump as to or away depending on clamp angle
for (index in 1:nrow(kr)) {
  if (kr$TargetJump[index] == 0.01) {
    kr$TJ[index] = "Jump In Place"
  } else if (kr$TargetJump[index] == kr$ClampAngle[index]) {
    kr$TJ[index] = "Jump To"
  } else if (kr$TargetJump[index] == -1*kr$ClampAngle[index]) {
    kr$TJ[index] = "Jump Away"
  } else if (kr$TargetJump[index] == 0) {
    kr$TJ[index] = "No Jump"
  }
}

kr$TJ = factor(kr$TJ, levels=c("Jump Away", "No Jump", "Jump In Place", "Jump To"))
kr$sub = as.factor(kr$Subject)
kr$ClampAngle = as.factor(kr$ClampAngle)
kr$reachAngle = as.numeric(kr$HandError)
```

```{r}
# initial preprocessing -- remove outliers, baseline subtraction according to strategy in Kim et al., 2019 elife
row.names(kr) <- NULL # reset indices

# find and remove outliers
numBadTrials = vector()
tgt_SDs = vector()
badTrialRows = c() # need to keep list of bad trials for later
for (s in unique(kr$sub)) {
  badTrialCounter = 0
  thisdata = subset(kr, sub==s)
  smoothed_hand = smooth(thisdata$reachAngle)
  detrended = thisdata$reachAngle - smoothed_hand
  tgt_SDs[s] = sd(detrended, na.rm = T)
  for (i in 1:length(detrended)) {
    if (!is.na(thisdata$reachAngle[i])) {
      if ((abs(detrended[i]) > 3*tgt_SDs[s]) | (abs(thisdata$reachAngle[i]) > 90) | (thisdata$FalseStart[i] == 1)) { # also exclude trials with a false start (no target, so would have had a washout reach in)
        badTrialRows = c(badTrialRows, rownames(thisdata)[i]) # log original df index for later
        badTrialCounter = badTrialCounter + 1 # update bad trial counter
      }
    }
  }
  
  numBadTrials[s] = badTrialCounter
}

kr$reachAngle_raw = kr$reachAngle # preserve raw reach angles
for (val in badTrialRows) {
  kr$reachAngle[as.numeric(val)] = NA # replace excluded values with NA
}


```

```{r}
# compute STL on each trial
for (t in 1:nrow(kr)) {
  if (kr$TrialNum[t] == 904) { # last trial of this person's training session - no STL measured for this error
    kr$STL[t] = NA
  } else {
    kr$STL[t] = kr$reachAngle[t+1] - kr$reachAngle[t]
  }
}
```


```{r}
# for each subject, get median STL response to each condition
sub = c()
clamp = c()
jump = c()
stl = c()
clampvals = c(-4, 4)
jumpvals = c("Jump Away", "No Jump", "Jump In Place", "Jump To")
for (s in unique(kr$sub)) {
  thisdata = subset(kr, sub==s)
  
  for (c in clampvals) {
    subset4 = subset(thisdata, ClampAngle==c)
    
    for (j in jumpvals) {
      subset4JumpAway = subset(subset4, TJ==j)
      sub = append(sub,s)
      clamp = append(clamp, c)
      jump = append(jump, j)
      stl = append(stl, median(subset4JumpAway$STL, na.rm = TRUE))
    }
  }
}

subjectwise = data.frame(sub, clamp, jump, stl)

# collapse across jump type
sub = c()
clamp = c()
stl = c()
for (s in unique(kr$sub)) {
  thisdata = subset(subjectwise, sub==s)
  
  for (c in clampvals) {
    subset4 = subset(thisdata, clamp==c)
    
    sub = append(sub,s)
    clamp = append(clamp, c)
    stl = append(stl, mean(subset4$stl, na.rm = TRUE))
  }
}
subjectwise_ignoreJump = data.frame(sub, clamp, stl)


# collapse across clamp direction
sub = c()
jump = c()
stl = c()
for (s in unique(kr$sub)) {
  thisdata = subset(subjectwise, sub==s)
  
  for (j in jumpvals) {
    pos4stl = thisdata$stl[thisdata$jump==j & thisdata$clamp==4]
    neg4stl = thisdata$stl[thisdata$jump==j & thisdata$clamp==-4]
    sub = append(sub,s)
    jump = append(jump, j)
    stl = append(stl, mean(c(pos4stl*-1, neg4stl), na.rm = TRUE))
  }
}
subjectwise_ignoreClampDir = data.frame(sub, jump, stl)

```

```{r}
# confirm that there is appropriate adaptation
clamp.aov <- anova_test(
  data = subjectwise_ignoreJump,
  dv = stl,
  wid = sub,
  within = clamp)
get_anova_table(clamp.aov)
pairedTAndCohensD(subset(subjectwise_ignoreJump, clamp==4)$stl, subset(subjectwise_ignoreJump, clamp==-4)$stl)

lrn_smry = ddply(subjectwise_ignoreJump, .(clamp), summarise,
                        stl_mean = mean(stl),
                        stl_se = sd(stl)/sqrt(15))
lrn_smry$clamp = as.factor(lrn_smry$clamp)


plot_dirSTL = ggplot() +  geom_point(data=lrn_smry, aes(y=stl_mean, x=clamp), size = 3) + geom_errorbar(data=lrn_smry, aes(y=stl_mean, x=clamp, ymin = stl_mean - stl_se,ymax = stl_mean + stl_se), size = 1,  width = 0) + #geom_boxplot(data=early_lr, aes(y=lr, x=condition, color = condition), outlier.shape=NA) + scale_color_manual(values = custom_palette) + scale_fill_manual(values = custom_palette) +
  ylab("STL \n(degrees)") +
  xlab("Error-Clamp") +
  ylim(-2, 2)+
  theme(legend.position="none")

plot_dirSTL

write.csv(lrn_smry,"output_fig4PanelB_STLXJump_meanSEM.csv", row.names = TRUE)
```

```{r}
# ANOVA
TJ.aov <- anova_test(
  data = subjectwise_ignoreClampDir,
  dv = stl,
  wid = sub,
  within = jump)
get_anova_table(TJ.aov)
jumpA = c()
jumpB = c()
t = c()
p = c()
d = c()

thisA = "Jump Away"
thisB = "No Jump"
statout = pairedTAndCohensD(subset(subjectwise_ignoreClampDir, jump == thisA)$stl,
                    subset(subjectwise_ignoreClampDir, jump == thisB)$stl) # returns t, df, p, and cohen's d
jumpA = append(jumpA, thisA)
jumpB = append(jumpB, thisB)
t = append(t, statout[1])
p = append(p, statout[3])
d = append(d, statout[4])

thisB = "Jump In Place"
statout = pairedTAndCohensD(subset(subjectwise_ignoreClampDir, jump == thisA)$stl,
                    subset(subjectwise_ignoreClampDir, jump == thisB)$stl) # returns t, df, p, and cohen's d
jumpA = append(jumpA, thisA)
jumpB = append(jumpB, thisB)
t = append(t, statout[1])
p = append(p, statout[3])
d = append(d, statout[4])

thisB = "Jump To"
statout = pairedTAndCohensD(subset(subjectwise_ignoreClampDir, jump == thisA)$stl,
                    subset(subjectwise_ignoreClampDir, jump == thisB)$stl) # returns t, df, p, and cohen's d
jumpA = append(jumpA, thisA)
jumpB = append(jumpB, thisB)
t = append(t, statout[1])
p = append(p, statout[3])
d = append(d, statout[4])

thisA = "No Jump"
thisB = "Jump In Place"
statout = pairedTAndCohensD(subset(subjectwise_ignoreClampDir, jump == thisA)$stl,
                    subset(subjectwise_ignoreClampDir, jump == thisB)$stl) # returns t, df, p, and cohen's d
jumpA = append(jumpA, thisA)
jumpB = append(jumpB, thisB)
t = append(t, statout[1])
p = append(p, statout[3])
d = append(d, statout[4])

thisB = "Jump To"
statout = pairedTAndCohensD(subset(subjectwise_ignoreClampDir, jump == thisA)$stl,
                    subset(subjectwise_ignoreClampDir, jump == thisB)$stl) # returns t, df, p, and cohen's d
jumpA = append(jumpA, thisA)
jumpB = append(jumpB, thisB)
t = append(t, statout[1])
p = append(p, statout[3])
d = append(d, statout[4])

thisA = "Jump In Place"
statout = pairedTAndCohensD(subset(subjectwise_ignoreClampDir, jump == thisA)$stl,
                    subset(subjectwise_ignoreClampDir, jump == thisB)$stl) # returns t, df, p, and cohen's d
jumpA = append(jumpA, thisA)
jumpB = append(jumpB, thisB)
t = append(t, statout[1])
p = append(p, statout[3])
d = append(d, statout[4])

posthocs = data.frame(jumpA, jumpB, t, p, d)
posthocs$padj = p.adjust(posthocs$p, method='fdr')


jump_smry = ddply(subjectwise_ignoreClampDir, .(jump), summarise,
                        stl_mean = mean(stl),
                        stl_se = sd(stl)/sqrt(15))
jump_smry$jump = factor(jump_smry$jump, c("Jump Away", "No Jump", "Jump In Place", "Jump To"))


plot_jumpSTL = ggplot() +  geom_point(data=jump_smry, aes(y=stl_mean, x=jump), size = 3) + geom_errorbar(data=jump_smry, aes(y=stl_mean, x=jump, ymin = stl_mean - stl_se,ymax = stl_mean + stl_se), size = 1,  width = 0) + #geom_boxplot(data=early_lr, aes(y=lr, x=condition, color = condition), outlier.shape=NA) + scale_color_manual(values = custom_palette) + scale_fill_manual(values = custom_palette) +
  ylab("STL \n(degrees)") +
  xlab("Target Jump") +
  ylim(0, 2)+
  theme(legend.position="none")

plot_jumpSTL

write.csv(jump_smry,"output_fig4PanelC_STLXJump_meanSEM.csv", row.names = TRUE)
```



```{r}
ggarrange(plot_dirSTL, plot_jumpSTL, ncol=2, legend=NULL)
```