---
title: "analysis_fig5_tsbattery"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(dplyr)
library(plyr)
library(ggplot2)
library(cowplot)
library(ggpubr)
library(rstatix)
library(effsize)
```

```{r}
# User-specific TODO
setwd('C:/Users/olivia/Documents/GitHub/TaskSuccessRewardImplicitAdapt') # TODO: go to appropriate working directory
```

```{r}
# custom functions

# dupe MATLAB's smooth function with window = 5
smooth <- function(y ){
  h <- c(head(y, 1), mean(head(y, 3), na.rm=T))
  t <- c(mean(tail(y, 3), na.rm=T), tail(y, 1))
  m <- c()
  for (i in 3:(length(y)-2)) {
    m <- c(m, mean(y[i-2:i+2], na.rm=T))
  }
  c(h, m, t)
}

pairedTAndCohensD <- function(dataA, dataB) {
  testout = t.test(dataA, dataB, paired = TRUE, var.equal=TRUE) # use Student's t-test
  t = testout$statistic
  df = testout$parameter
  p = testout$p.value
  
  testout = cohen.d(dataA, dataB, paired = TRUE)
  d = testout$estimate
  return(c(t, df, p, d))
}

```


```{r}
# load data
kr = read.csv("data_fig5_TargetSizeTargetJump.csv")
kr = kr[kr$TrialNum>103,] # omit data from the baseline and tutorial
kr$TaskSuccess = factor(kr$TrialLabel, levels=c("Miss", "Hit", "Jump To"))
kr$sub = as.factor(kr$Subject)
kr$ClampAngle = as.factor(kr$ClampAngle)
kr$reachAngle = as.numeric(kr$HandError)
```

```{r}
# initial preprocessing -- remove outliers, baseline subtraction according to strategy in Kim et al., 2019 elife
row.names(kr) = NULL

# find and remove outliers
numBadTrials = vector()
tgt_SDs = vector()
badTrialRows = c() # need to keep list of bad trials for later
for (s in unique(kr$sub)) {
  badTrialCounter = 0
  thisdata = subset(kr, sub==s)
  smoothed_hand = smooth(thisdata$reachAngle)
  detrended = thisdata$reachAngle - smoothed_hand
  tgt_SDs[s] = sd(detrended, na.rm = T)
  for (i in 1:length(detrended)) {
    if (!is.na(thisdata$reachAngle[i])) {
      if ((abs(detrended[i]) > 3*tgt_SDs[s]) | (abs(thisdata$reachAngle[i]) > 90) | (thisdata$FalseStart[i] == 1)) { # also exclude trials with a false start (no target, so would have had a washout reach in)
        badTrialRows = c(badTrialRows, rownames(thisdata)[i]) # log original df index for later
        badTrialCounter = badTrialCounter + 1 # update bad trial counter
      }
    }
  }
  
  numBadTrials[s] = badTrialCounter
}

kr$reachAngle_raw = kr$reachAngle # preserve raw reach angles
for (val in badTrialRows) {
  kr$reachAngle[as.numeric(val)] = NA # replace excluded values with NA
}


```

```{r}
# compute STL on each trial
for (t in 1:nrow(kr)) {
  if (kr$TrialNum[t] == 968) { # last trial of this person's training session - no STL measured for this error
    kr$STL[t] = NA
  } else {
    kr$STL[t] = kr$reachAngle[t+1] - kr$reachAngle[t]
  }
}
```


```{r}
# for each subject, get median STL response to each condition
sub = c()
clamp = c()
success = c()
stl = c()
clampvals = c(-10.5, -8.75, -7, -5.25, -3.5, -1.75, 1.75, 3.5, 5.25, 7, 8.75, 10.5)
successvals = c("Miss", "Hit", "Jump To")
for (s in unique(kr$sub)) {
  thisdata = subset(kr, sub==s)
  
  for (c in clampvals) {
    subsetC = subset(thisdata, ClampAngle==c)
    
    for (j in successvals) {
      subsetCSuccess = subset(subsetC, TaskSuccess==j)
      sub = append(sub,s)
      clamp = append(clamp, c)
      success = append(success, j)
      stl = append(stl, median(subsetCSuccess$STL, na.rm = TRUE))
    }
  }
}

subjectwise = data.frame(sub, clamp, success, stl)

# collapse across success type
sub = c()
clamp = c()
stl = c()
for (s in unique(kr$sub)) {
  thisdata = subset(subjectwise, sub==s)
  
  for (c in clampvals) {
    subset4 = subset(thisdata, clamp==c)
    
    sub = append(sub,s)
    clamp = append(clamp, c)
    stl = append(stl, mean(subset4$stl, na.rm = TRUE))
  }
}
subjectwise_ignoreJump = data.frame(sub, clamp, stl)


# collapse across clamp direction
sub = c()
success = c()
clamp = c()
stl = c()
absclampvals = c(1.75, 3.5, 5.25, 7, 8.75, 10.5)
for (s in unique(kr$sub)) {
  thisdata = subset(subjectwise, sub==s)
  
  for (c in absclampvals) {
    for (j in successvals) {
      posstl = thisdata$stl[thisdata$success==j & thisdata$clamp==c]
      negstl = thisdata$stl[thisdata$success==j & thisdata$clamp==-1*c]
      sub = append(sub,s)
      success = append(success, j)
      clamp = append(clamp, c)
      stl = append(stl, mean(c(posstl*-1, negstl), na.rm = TRUE))
    }
  }
}
subjectwise_ignoreClampDir = data.frame(sub, success, clamp, stl)

```

```{r}
# confirm that there is appropriate adaptation
lrn_smry = ddply(subjectwise_ignoreJump, .(clamp), summarise,
                        stl_mean = mean(stl),
                        stl_se = sd(stl)/sqrt(42))
lrn_smry$clamp = as.factor(lrn_smry$clamp)


plot_dirSTL = ggplot() +  geom_point(data=lrn_smry, aes(y=stl_mean, x=clamp), size = 3) + geom_errorbar(data=lrn_smry, aes(y=stl_mean, x=clamp, ymin = stl_mean - stl_se,ymax = stl_mean + stl_se), size = 1,  width = 0) + #geom_boxplot(data=early_lr, aes(y=lr, x=condition, color = condition), outlier.shape=NA) + scale_color_manual(values = custom_palette) + scale_fill_manual(values = custom_palette) +
  ylab("STL \n(degrees)") +
  xlab("Error-Clamp") +
  ylim(-2, 2)+
  theme(legend.position="none")

plot_dirSTL

write.csv(lrn_smry,"output_fig5PanelA_STLXClamp_meanSEM.csv", row.names = TRUE)
```

```{r}
# ANOVA
TS.aov <- anova_test(
  data = subjectwise_ignoreClampDir,
  dv = stl,
  wid = sub,
  within = c(success, clamp))
get_anova_table(TS.aov)


successA = c()
clampA = c()
successB = c()
clampB = c()
t = c()
p = c()
d = c()

tsuccessA = "Miss"
tclampA = NA
tsuccessB = "Hit"
tclampB = NA

tempA = subset(subjectwise_ignoreClampDir, success == tsuccessA)
tempA = tapply(tempA$stl, tempA$sub, mean, na.rm=T)
tempB = subset(subjectwise_ignoreClampDir, success == tsuccessB)
tempB = tapply(tempB$stl, tempB$sub, mean, na.rm=T)

statout = pairedTAndCohensD(tempA, tempB) # returns t, df, p, and cohen's d
successA = append(successA, tsuccessA)
successB = append(successB, tsuccessB)
clampA = append(clampA, tclampA)
clampB = append(clampB, tclampB)
t = append(t, statout[1])
p = append(p, statout[3])
d = append(d, statout[4])


tsuccessB = "Jump To"
tempB = subset(subjectwise_ignoreClampDir, success == tsuccessB)
tempB = tapply(tempB$stl, tempB$sub, mean, na.rm=T)

statout = pairedTAndCohensD(tempA, tempB) # returns t, df, p, and cohen's d
successA = append(successA, tsuccessA)
successB = append(successB, tsuccessB)
clampA = append(clampA, tclampA)
clampB = append(clampB, tclampB)
t = append(t, statout[1])
p = append(p, statout[3])
d = append(d, statout[4])

tsuccessA = "Hit"
tsuccessB = "Jump To"
tempA = subset(subjectwise_ignoreClampDir, success == tsuccessA)
tempA = tapply(tempA$stl, tempA$sub, mean, na.rm=T)
tempB = subset(subjectwise_ignoreClampDir, success == tsuccessB)
tempB = tapply(tempB$stl, tempB$sub, mean, na.rm=T)

statout = pairedTAndCohensD(tempA, tempB) # returns t, df, p, and cohen's d
successA = append(successA, tsuccessA)
successB = append(successB, tsuccessB)
clampA = append(clampA, tclampA)
clampB = append(clampB, tclampB)
t = append(t, statout[1])
p = append(p, statout[3])
d = append(d, statout[4])


tsuccessA = "Miss"
tsuccessB = "Hit"
cohensD = c()
vsMiss = c()
vsclamp = c()
for (c in absclampvals) {
  statout = pairedTAndCohensD(subset(subjectwise_ignoreClampDir, clamp == c & success == tsuccessA)$stl,
                              subset(subjectwise_ignoreClampDir, clamp == c & success == tsuccessB)$stl) # returns t, df, p, and cohen's d
  successA = append(successA, tsuccessA)
  successB = append(successB, tsuccessB)
  clampA = append(clampA, c)
  clampB = append(clampB, c)
  t = append(t, statout[1])
  p = append(p, statout[3])
  d = append(d, statout[4])
  cohensD = append(cohensD, statout[4])
  vsMiss = append(vsMiss, tsuccessB)
  vsclamp = append(vsclamp, c)
}

tsuccessA = "Miss"
tsuccessB = "Jump To"
for (c in absclampvals) {
  statout = pairedTAndCohensD(subset(subjectwise_ignoreClampDir, clamp == c & success == tsuccessA)$stl,
                              subset(subjectwise_ignoreClampDir, clamp == c & success == tsuccessB)$stl) # returns t, df, p, and cohen's d
  successA = append(successA, tsuccessA)
  successB = append(successB, tsuccessB)
  clampA = append(clampA, c)
  clampB = append(clampB, c)
  t = append(t, statout[1])
  p = append(p, statout[3])
  d = append(d, statout[4])
  cohensD = append(cohensD, statout[4])
  vsMiss = append(vsMiss, tsuccessB)
  vsclamp = append(vsclamp, c)
}

tsuccessA = "Hit"
tsuccessB = "Jump To"
for (c in absclampvals) {
  statout = pairedTAndCohensD(subset(subjectwise_ignoreClampDir, clamp == c & success == tsuccessA)$stl,
                              subset(subjectwise_ignoreClampDir, clamp == c & success == tsuccessB)$stl) # returns t, df, p, and cohen's d
  successA = append(successA, tsuccessA)
  successB = append(successB, tsuccessB)
  clampA = append(clampA, c)
  clampB = append(clampB, c)
  t = append(t, statout[1])
  p = append(p, statout[3])
  d = append(d, statout[4])
}

posthocs = data.frame(successA, clampA, successB, clampB, t, p, d)
posthocs$padj = p.adjust(posthocs$p, method='fdr')
posthocs$signif = posthocs$padj < 0.05

effsizeForPlot = data.frame(vsMiss, vsclamp, cohensD)


success_smry = ddply(subjectwise_ignoreClampDir, .(success), summarise,
                        stl_mean = mean(stl),
                        stl_se = sd(stl)/sqrt(42))
success_smry$success = factor(success_smry$success, c("Miss", "Hit", "Jump To"))


plot_successSTL = ggplot() +  geom_point(data=success_smry, aes(y=stl_mean, x=success), size = 3) + geom_errorbar(data=success_smry, aes(y=stl_mean, x=success, ymin = stl_mean - stl_se,ymax = stl_mean + stl_se), size = 1,  width = 0) + #geom_boxplot(data=early_lr, aes(y=lr, x=condition, color = condition), outlier.shape=NA) + scale_color_manual(values = custom_palette) + scale_fill_manual(values = custom_palette) +
  ylab("STL \n(degrees)") +
  xlab("Task Success") +
  ylim(0, 2)+
  theme(legend.position="none")

plot_successSTL

write.csv(success_smry,"output_fig5PanelB_STLXSuccess_meanSEM.csv", row.names = TRUE)


successClamp_smry = ddply(subjectwise_ignoreClampDir, .(success, clamp), summarise,
                        stl_mean = mean(stl),
                        stl_se = sd(stl)/sqrt(42))
successClamp_smry$success = factor(successClamp_smry$success, c("Miss", "Hit", "Jump To"))

plot_successClampSTL = ggplot() +  geom_point(data=successClamp_smry, aes(y=stl_mean, x=clamp, color=success), size = 3) + geom_errorbar(data=successClamp_smry, aes(y=stl_mean, x=clamp, color=success, ymin = stl_mean - stl_se,ymax = stl_mean + stl_se), size = 1,  width = 0) + #geom_boxplot(data=early_lr, aes(y=lr, x=condition, color = condition), outlier.shape=NA) + scale_color_manual(values = custom_palette) + scale_fill_manual(values = custom_palette) +
  ylab("STL \n(degrees)") +
  xlab("Error-Clamp (degrees)") +
  ylim(0, 2)

plot_successClampSTL

write.csv(successClamp_smry,"output_fig5PanelC_STLXSuccessClamp_meanSEM.csv", row.names = TRUE)


xval = c(1.25,11)
small = c(0.2, 0.2)
medium = c(0.5, 0.5)
large = c(0.8, 0.8)

plot_vsMissEffsize = ggplot() +  geom_point(data=effsizeForPlot, aes(y=cohensD, x=vsclamp, color=vsMiss), size = 3) + #geom_boxplot(data=early_lr, aes(y=lr, x=condition, color = condition), outlier.shape=NA) + scale_color_manual(values = custom_palette) + scale_fill_manual(values = custom_palette) +
  geom_line(data=effsizeForPlot, aes(y=cohensD, x=vsclamp, color=vsMiss)) +
  geom_line(data=data.frame(xval,small), aes(y=small, x=xval)) +
  geom_line(data=data.frame(xval,medium), aes(y=medium, x=xval)) +
  geom_line(data=data.frame(xval,large), aes(y=large, x=xval)) +
  ylab("Effect Size (Cohen's d)") +
  xlab("Error-Clamp (degrees)") +
  ylim(0, 1)

plot_vsMissEffsize

write.csv(effsizeForPlot,"output_fig5PanelD_effsizeXSuccessClamp_mean.csv", row.names = TRUE)
```



```{r}
ggarrange(ggarrange(plot_dirSTL, plot_successClampSTL, ncol=2),
          ggarrange(plot_successSTL, plot_vsMissEffsize, ncol=2),
          nrow=2)
```