---
title: "analysis_fig1_moneytargetsize"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(dplyr)
library(plyr)
library(ggplot2)
library(cowplot)
library(ggpubr)
library(rstatix)
library(effsize)
library(psych)
```

```{r}
# load data
km = read.csv("C:/Users/kimol/Documents/GitHub/RewardTaskSuccess/data_fig1_moneytargetsize.csv") # TODO: update directory so it works with your setup
km$target = as.factor(km$targAngle)
km$sub = as.factor(km$subject)
#comment this line if you don't want to use maxvelAngle
km$reachAngle = km$maxvelAngle
```


```{r}
# custom functions

# dupe MATLAB's smooth function with window = 5
smooth <- function(y ){
  h <- c(head(y, 1), mean(head(y, 3), na.rm=T))
  t <- c(mean(tail(y, 3), na.rm=T), tail(y, 1))
  m <- c()
  for (i in 3:(length(y)-2)) {
    m <- c(m, mean(y[i-2:i+2], na.rm=T))
  }
  c(h, m, t)
}

unpairedTAndCohensD <- function(dataA, dataB) {
  testout = t.test(dataA, dataB, paired = FALSE, var.equal = TRUE) # use Student's t-test
  t = testout$statistic
  df = testout$parameter
  p = testout$p.value
  
  testout = effsize::cohen.d(dataA, dataB, paired = FALSE)
  d = testout$estimate
  return(c(t, df, p, d))
}

```


```{r}
# initial preprocessing -- remove outliers, baseline subtraction

# find and remove outliers
targAngles = unique(km$target)
numBadTrials = vector()
tgt_SDs = data.frame(matrix(NA, length(unique(km$sub)), length(targAngles)))
badTrialRows = c() # need to keep list of bad trials for later
for (s in unique(km$sub)) {
  badTrialCounter = 0
  t = 0
  for(targ in targAngles){
    t = t+1
    thisdata = subset(km, sub==s & target==targ)
    smoothed_hand = smooth(thisdata$reachAngle)
    detrended = thisdata$reachAngle - smoothed_hand
    tgt_SDs[s,t] = sd(detrended, na.rm = T)
    for (i in 1:length(detrended)) {
      if (!is.na(thisdata$reachAngle[i])) {
        if ((abs(detrended[i]) > 3*tgt_SDs[s,t]) | (abs(thisdata$reachAngle[i]) > 90)) {
          badTrialRows = c(badTrialRows, rownames(thisdata)[i]) # log original df index for later
          badTrialCounter = badTrialCounter + 1 # update bad trial counter
        }
      }
    }
  }
  numBadTrials[s] = badTrialCounter
}
km$reachAngle_raw = km$reachAngle # preserve raw reach angles
for (val in badTrialRows) {
  km$reachAngle[as.numeric(val)] = NA # replace excluded values with NA
}

km.base = subset(km, trialNum > 40 & trialNum<81) # baseline trials with feedback

#subtract baseline biases for each participant (targetwise)
targAngles = unique(km$target)
for(targ in targAngles){
  km_targ.base = subset(km.base, targAngle == targ)
  km.sub_targ_bias = tapply(km_targ.base$reachAngle, km_targ.base$sub, mean, na.rm = T)
  
  for(s in unique(km$subject)){
    km$reachAngle[km$subject == s & km$targAngle == targ] = km$reachAngle[km$subject == s & km$targAngle == targ] - km.sub_targ_bias[s]
  }
}

```

```{r}
# subset data
km$bin = as.factor(km$bin)
str_p2d = subset(km, condition == 1)
str_d2p = subset(km, condition == 2)
hit_p2d = subset(km, condition == 3)
hit_d2p = subset(km, condition == 4)
```

```{r}
#binned learning curve
binSubjectData <- function(dfin){
  sub = c()
  bin = c()
  reachAngle = c()
  for (s in unique(dfin$sub)){
    tempdata = subset(dfin, sub==s)
    binneddata = tapply(tempdata$reachAngle, tempdata$bin, mean, na.rm=T)
    for (b in 1:length(binneddata)) {
      sub = c(sub, s)
      bin = c(bin, as.numeric(rownames(binneddata)[b]))
      reachAngle = c(reachAngle, binneddata[b])
    }
  }
  subjectwiseBins = data.frame(sub, bin, reachAngle)
  return(subjectwiseBins)
}

str_p2d_binned = binSubjectData(str_p2d)
str_p2d_bin_lc = tapply(str_p2d_binned$reachAngle, str_p2d_binned$bin, mean, na.rm = T)
str_p2d_bin_lc_ci = tapply(str_p2d_binned$reachAngle, str_p2d_binned$bin, sd, na.rm = T) /sqrt(length(unique(str_p2d_binned$sub)))

str_d2p_binned = binSubjectData(str_d2p)
str_d2p_bin_lc = tapply(str_d2p_binned$reachAngle, str_d2p_binned$bin, median, na.rm = T)
str_d2p_bin_lc_ci = tapply(str_d2p_binned$reachAngle, str_d2p_binned$bin, sd, na.rm = T) /sqrt(length(unique(str_d2p_binned$sub)))

hit_p2d_binned = binSubjectData(hit_p2d)
hit_p2d_bin_lc = tapply(hit_p2d_binned$reachAngle, hit_p2d_binned$bin, mean, na.rm = T)
hit_p2d_bin_lc_ci = tapply(hit_p2d_binned$reachAngle, hit_p2d_binned$bin, sd, na.rm = T) /sqrt(length(unique(hit_p2d$sub)))

hit_d2p_binned = binSubjectData(hit_d2p)
hit_d2p_bin_lc = tapply(hit_d2p_binned$reachAngle, hit_d2p_binned$bin, mean, na.rm = T)
hit_d2p_bin_lc_ci = tapply(hit_d2p_binned$reachAngle, hit_d2p_binned$bin, sd, na.rm = T) /sqrt(length(unique(hit_d2p_binned$sub)))

# this should get moved to the top for settings
theme_set(theme_cowplot())
custom_palette = c("#A6CEE3","#1F78B4", "#FB9A99", "#E31A1C")

binned_lcs = data.frame(
  condition = factor(c(rep("Miss p2d", 200), rep("Miss d2p", 200), 
                       rep("Hit p2d", 200), rep("Hit d2p", 200))),
  trial = c(1:200-0.6, 1:200-0.3, 1:200+0.3, 1:200+0.6),
  epAngle = c(str_p2d_bin_lc, str_d2p_bin_lc, hit_p2d_bin_lc, hit_d2p_bin_lc),
  sd = c(str_p2d_bin_lc_ci, str_d2p_bin_lc_ci, hit_p2d_bin_lc_ci, hit_d2p_bin_lc_ci)
)
plot_lcs = ggplot(data = binned_lcs, aes(x = trial, y=epAngle, group=condition, color= condition)) + 
  geom_point() + 
  geom_vline(xintercept = 20, linetype = "dashed") + 
  geom_vline(xintercept = 100, linetype = "dashed") + 
  geom_vline(xintercept = 180, linetype = "dashed")+ 
  geom_ribbon(aes(x = trial, ymin = epAngle - sd, ymax = epAngle + sd, fill = condition), inherit.aes = F)+
  scale_color_manual(values = custom_palette) +
  scale_fill_manual(values = custom_palette) +
  ylab("Hand Angle \n(degrees)") +
  xlab("Cycle (4 trials)")
plot_lcs

# save data that went into the figure
learningCurveDF = data.frame(str_p2d_bin_lc, str_p2d_bin_lc_ci,
                             str_d2p_bin_lc, str_d2p_bin_lc_ci,
                             hit_p2d_bin_lc, hit_p2d_bin_lc_ci,
                             hit_d2p_bin_lc, hit_d2p_bin_lc_ci)
write.csv(learningCurveDF,"output_fig1PanelE_binnedLC_meanSEM.csv", row.names = FALSE)
```


```{r}
## early learning rates
getEarlyLR <- function(dfin) {
  # this approach is what Kim et al., 2019 did
  output = vector()
  for (s in unique(dfin$sub)) {
    tempvals = subset(dfin[dfin$sub==s,], bin < 30 & bin > 24)
    lastbin = tapply(tempvals$reachAngle, tempvals$bin, mean, na.rm = T)
    output[s] = mean(lastbin)/5
  }
  return(output)
}

str_p2d_early_lr = getEarlyLR(str_p2d_binned)
str_d2p_early_lr = getEarlyLR(str_d2p_binned)
hit_p2d_early_lr = getEarlyLR(hit_p2d_binned)
hit_d2p_early_lr = getEarlyLR(hit_d2p_binned)
# arrange into dataframe for 2 way ANOVA
sub = 1:64
targetSize = c(rep("Small", 32), rep("Big", 32))
rewardAvailable = c(rep("penny", 16), rep("dollar", 16), rep("penny", 16), rep("dollar", 16))
earlyLR = c(str_p2d_early_lr, str_d2p_early_lr,
              hit_p2d_early_lr, hit_d2p_early_lr)
earlyLRDF = data.frame(sub, targetSize, rewardAvailable, earlyLR)
earlyLRDF$targetSize = as.factor(earlyLRDF$targetSize)
earlyLRDF$rewardAvailable = as.factor(earlyLRDF$rewardAvailable)
earlyLRDF$sub = as.factor(earlyLRDF$sub)
# ggboxplot(earlyLRDF, x = "targetSize", y = "earlyLR", color = "rewardAvailable",
#           palette = c("#00AFBB", "#E7B800")) # boxplot early learning rate ("earlyLR") by task success groups ("targetSize"). color box plots by the second grouping factor of the reward available ("rewardAvailable")
earlyLR.aov2Way <- anova_test(
  data = earlyLRDF,
  formula = earlyLR ~ targetSize + rewardAvailable + targetSize*rewardAvailable,
  dv = earlyLR)
get_anova_table(earlyLR.aov2Way)


early_lr = data.frame(
  condition = c(rep("Straddle\nPenny", 16), rep("Straddle\nDollar", 16), 
                rep("Hit\nPenny", 16), rep("Hit\nDollar", 16)),
  lr = c(as.numeric(str_p2d_early_lr), as.numeric(str_d2p_early_lr), as.numeric(hit_p2d_early_lr), as.numeric(hit_d2p_early_lr))
)
early_lr_smry = ddply(early_lr, .(condition), summarise,
                      early_mean = mean(lr, na.rm = T),
                      early_se = sd(lr, na.rm = T)/sqrt(16))

plot_lr = ggplot() +  geom_point(data=early_lr_smry, aes(y=early_mean, x=condition, color = condition), size = 3) + geom_errorbar(data=early_lr_smry, aes(y=early_mean, x=condition, ymin = early_mean - early_se,ymax = early_mean + early_se, color = condition), size = 1,  width = 0) + #geom_boxplot(data=early_lr, aes(y=lr, x=condition, color = condition), outlier.shape=NA) +
  scale_color_manual(values = custom_palette) +
  scale_fill_manual(values = custom_palette) +
  ylab("Learning Rate \n(degrees/bin)") +
  xlab("Condition") +
  ylim(0.25, 1.25)+
  theme(legend.position="none")

plot_lr

# plot_lr = ggplot(data=early_lr, aes(y=lr, x=condition, color = condition)) + 
#   stat_summary(fun.data=MinMeanSEMMax, geom="boxplot")+
#   scale_color_manual(values = custom_palette) +
#   scale_fill_manual(values = custom_palette) +
#   ylab("Learning Rate \n(degrees/bin)") +
#   xlab("Condition") +
#   ylim(0, 1.25)+
#   theme(legend.position="none")
# 
# plot_lr

write.csv(early_lr_smry,"output_fig1PanelF_earlyLR_meanSEM.csv", row.names = TRUE)
```

```{r}

##late asymptotes (clamp 1)
str_p2d.late1 = subset(str_p2d_binned, bin>90 & bin<101)
hit_p2d.late1 = subset(hit_p2d_binned, bin>90 & bin<101)
str_p2d_late1_asym = tapply(str_p2d.late1$reachAngle, str_p2d.late1$sub, mean, na.rm = T)
hit_p2d_late1_asym = tapply(hit_p2d.late1$reachAngle, hit_p2d.late1$sub, mean, na.rm = T)
str_d2p.late1 = subset(str_d2p_binned, bin>90 & bin<101)
hit_d2p.late1 = subset(hit_d2p_binned, bin>90 & bin<101)
str_d2p_late1_asym = tapply(str_d2p.late1$reachAngle, str_d2p.late1$sub, mean, na.rm = T)
hit_d2p_late1_asym = tapply(hit_d2p.late1$reachAngle, hit_d2p.late1$sub, mean, na.rm = T)

# arrange into dataframe for 2 way ANOVA
sub = 1:64
targetSize = c(rep("Small", 32), rep("Big", 32))
rewardAvailable = c(rep("penny", 16), rep("dollar", 16), rep("penny", 16), rep("dollar", 16))
asym1 = c(str_p2d_late1_asym, str_d2p_late1_asym,
              hit_p2d_late1_asym, hit_d2p_late1_asym)
asym1DF = data.frame(sub, targetSize, rewardAvailable, asym1)
asym1DF$targetSize = as.factor(asym1DF$targetSize)
asym1DF$rewardAvailable = as.factor(asym1DF$rewardAvailable)
# ggboxplot(asym1DF, x = "targetSize", y = "asym1", color = "rewardAvailable",
#           palette = c("#00AFBB", "#E7B800")) # boxplot initial asymptote ("asym1") by task success groups ("targetSize"). color box plots by the second grouping factor of the reward available ("rewardAvailable")
asym1.aov2Way <- anova_test(
  data = asym1DF,
  formula = asym1 ~ targetSize + rewardAvailable + targetSize*rewardAvailable,
  dv = asym1)
get_anova_table(asym1.aov2Way)
unpairedTAndCohensD(asym1DF$asym1[asym1DF$targetSize=="Small"],
                    asym1DF$asym1[asym1DF$targetSize=="Big"])


#asym figures
asymptotes = data.frame(
  condition = c(rep("Straddle\nPenny", 16), rep("Straddle\nDollar", 16), 
                rep("Hit\nPenny", 16), rep("Hit\nDollar", 16)),
  asym = c(as.numeric(str_p2d_late1_asym), as.numeric(str_d2p_late1_asym), as.numeric(hit_p2d_late1_asym), as.numeric(hit_d2p_late1_asym))
)
asym_smry = ddply(asymptotes, .(condition), summarise,
                        asym_mean = mean(asym),
                        asym_se = sd(asym)/sqrt(16))

plot_asym = ggplot() +  geom_point(data=asym_smry, aes(y=asym_mean, x=condition, color = condition), size = 3) +  geom_errorbar(data=asym_smry, aes(y=asym_mean, x=condition, ymin = asym_mean - asym_se,ymax = asym_mean + asym_se, color = condition), size = 1, width = 0) + #  geom_boxplot(data=asymptotes, aes(y=asym, x=condition, color = condition), outlier.shape=NA) +
  scale_color_manual(values = custom_palette) +
  scale_fill_manual(values = custom_palette) +
  ylab("Asymptote \n(degrees)") +
  xlab("Condition") +
  ylim(0,15)+
  theme(legend.position="none")
plot_asym

# plot_asym = ggplot(data=asymptotes, aes(y=asym, x=condition, color = condition)) +
#   stat_summary(fun.data=MinMeanSEMMax, geom="boxplot") +
#   scale_color_manual(values = custom_palette) +
#   scale_fill_manual(values = custom_palette) +
#   ylab("Asymptote \n(degrees)") +
#   xlab("Condition") +
#   ylim(0,15)+
#   theme(legend.position="none")
# plot_asym

write.csv(asym_smry,"output_fig1PanelG_asym1_meanSEM.csv", row.names = TRUE)
```

```{r}
#late asymptotes (clamp 2)
str_p2d.late2 = subset(str_p2d_binned, bin>170 & bin<181)
hit_p2d.late2 = subset(hit_p2d_binned, bin>170 & bin<181)
str_p2d_late2_asym = tapply(str_p2d.late2$reachAngle, str_p2d.late2$sub, mean, na.rm = T)
hit_p2d_late2_asym = tapply(hit_p2d.late2$reachAngle, hit_p2d.late2$sub, mean, na.rm = T)
str_d2p.late2 = subset(str_d2p_binned, bin>170 & bin<181)
hit_d2p.late2 = subset(hit_d2p_binned, bin>170 & bin<181)
str_d2p_late2_asym = tapply(str_d2p.late2$reachAngle, str_d2p.late2$sub, mean, na.rm = T)
hit_d2p_late2_asym = tapply(hit_d2p.late2$reachAngle, hit_d2p.late2$sub, mean, na.rm = T)

# arrange into dataframe for 2 way ANOVA
sub = 1:64
targetSize = c(rep("Small", 32), rep("Big", 32))
rewardAvailable = c(rep("dollar", 16), rep("penny", 16), rep("dollar", 16), rep("penny", 16))
asym2 = c(str_p2d_late2_asym, str_d2p_late2_asym,
              hit_p2d_late2_asym, hit_d2p_late2_asym)
asym2DF = data.frame(sub, targetSize, rewardAvailable, asym2)
asym2DF$targetSize = as.factor(asym2DF$targetSize)
asym2DF$rewardAvailable = as.factor(asym2DF$rewardAvailable)
# ggboxplot(asym2DF, x = "targetSize", y = "asym2", color = "rewardAvailable",
#           palette = c("#00AFBB", "#E7B800")) # boxplot initial asymptote ("asym1") by task success groups ("targetSize"). color box plots by the second grouping factor of the reward available ("rewardAvailable")

asymptotes2 = data.frame(
  condition = c(rep("Straddle\nPenny", 16), rep("Straddle\nDollar", 16), # labels here are a bit weird so will match up later... penny conditions got dollar in this time frame and vice versa
                rep("Hit\nPenny", 16), rep("Hit\nDollar", 16)),
  asym = c(as.numeric(str_p2d_late2_asym), as.numeric(str_d2p_late2_asym), as.numeric(hit_p2d_late2_asym), as.numeric(hit_d2p_late2_asym))
)

```

```{r}
#changes in asymptote
str_p2d_diff_asym = str_p2d_late2_asym - str_p2d_late1_asym
str_d2p_diff_asym = str_d2p_late2_asym - str_d2p_late1_asym
hit_p2d_diff_asym = hit_p2d_late2_asym - hit_p2d_late1_asym
hit_d2p_diff_asym = hit_d2p_late2_asym - hit_d2p_late1_asym
# put into df for ANOVA
sub = 1:64
targetSize = c(rep("Small", 32), rep("Big", 32))
rewardSwitch = c(rep("p2d", 16), rep("d2p", 16), rep("p2d", 16), rep("d2p", 16))
deltaAsym = c(str_p2d_diff_asym, str_d2p_diff_asym,
              hit_p2d_diff_asym, hit_d2p_diff_asym)
deltaAsymDF = data.frame(sub, targetSize, rewardSwitch, deltaAsym)
deltaAsymDF$targetSize = as.factor(deltaAsymDF$targetSize)
deltaAsymDF$rewardSwitch = as.factor(deltaAsymDF$rewardSwitch)
# ggboxplot(deltaAsymDF, x = "targetSize", y = "deltaAsym", color = "rewardSwitch",
#           palette = c("#00AFBB", "#E7B800")) # boxplot change in asymptote ("deltaAsym") by task success groups ("targetSize"). color box plots by the second grouping factor of the reward switch ("rewardSwitch")
deltaAsym.aov2Way <- anova_test(
  data = deltaAsymDF,
  formula = deltaAsym ~ targetSize + rewardSwitch + targetSize*rewardSwitch,
  dv = deltaAsym)
get_anova_table(deltaAsym.aov2Way)


#asym figures
delasymptotes = data.frame(
  condition = c(rep("Straddle\nPenny to Dollar", 16), rep("Straddle\nDollar to Penny", 16), 
                rep("Hit\nPenny to Dollar", 16), rep("Hit\nDollar to Penny", 16))
)
delasymptotes$del_asym = asymptotes2$asym - asymptotes$asym
delta_smry = ddply(delasymptotes, .(condition), summarise,
                        del_asym_mean = mean(del_asym),
                        del_asym_se = sd(del_asym)/sqrt(16))


plot_delasym = ggplot() +
  geom_point(data=delta_smry, aes(y=del_asym_mean, x=condition, color = condition), size = 3) + geom_errorbar(data=delta_smry, aes(y=del_asym_mean, x=condition, ymin = del_asym_mean - del_asym_se,ymax = del_asym_mean + del_asym_se, color = condition), size = 1, width = 0) + #geom_boxplot(data=delasymptotes, aes(y=del_asym, x=condition, color = condition), outlier.shape=NA) +
  scale_color_manual(values = custom_palette) +
  scale_fill_manual(values = custom_palette) +
  ylab("Change in Asymptote \n(degrees)") +
  xlab("Condition")+ 
  geom_hline(yintercept = 0, linetype = "dashed")+
  theme(legend.title = element_text(size=18), legend.text=element_text(size=16))+
  ylim(-4,4)+
  theme(legend.position="none")
plot_delasym


write.csv(delta_smry,"output_fig1PanelH_delta_meanSEM.csv", row.names = TRUE)
```


```{r}
#washout
getPctRet <- function(dfin) {
  # retention as % retained at end of 5 no-FB cycles
  wash = subset(dfin, bin == 185)
  lastcycle = subset(dfin, bin == 180)
  output = tapply(wash$reachAngle, wash$sub, mean, na.rm = T)/
    tapply(lastcycle$reachAngle, wash$sub, mean, na.rm = T)
  return(output)
}

str_p2d_wash = getPctRet(str_p2d_binned)
hit_p2d_wash = getPctRet(hit_p2d_binned)
str_d2p_wash = getPctRet(str_d2p_binned)
hit_d2p_wash = getPctRet(hit_d2p_binned)
# put into DF for ANOVA
sub = 1:64
targetSize = c(rep("Small", 32), rep("Big", 32))
rewardSwitch = c(rep("p2d", 16), rep("d2p", 16), rep("p2d", 16), rep("d2p", 16))
washRet = c(str_p2d_wash, str_d2p_wash,
              hit_p2d_wash, hit_d2p_wash)
washRetDF = data.frame(sub, targetSize, rewardSwitch, washRet)
washRetDF$targetSize = as.factor(washRetDF$targetSize)
washRetDF$rewardSwitch = as.factor(washRetDF$rewardSwitch)
# ggboxplot(washRetDF, x = "targetSize", y = "washRet", color = "rewardSwitch",
#           palette = c("#00AFBB", "#E7B800")) # boxplot retention ("washRet") by task success groups ("targetSize"). color box plots by the second grouping factor of the reward switch ("rewardSwitch")
washRet.aov2Way <- anova_test(
  data = washRetDF,
  formula = washRet ~ targetSize + rewardSwitch + targetSize*rewardSwitch,
  dv = washRet)
get_anova_table(washRet.aov2Way)


washout = data.frame(
  condition = c(rep("Straddle\nPenny to Dollar", 16), rep("Straddle\nDollar to Penny", 16), 
                rep("Hit\nPenny to Dollar", 16), rep("Hit\nDollar to Penny", 16)),
  wash = c(as.numeric(str_p2d_wash), as.numeric(str_d2p_wash), as.numeric(hit_p2d_wash), as.numeric(hit_d2p_wash))
)
wash_smry = ddply(washout, .(condition), summarise,
                        wash_mean = mean(wash),
                        wash_se = sd(wash)/sqrt(16))

plot_wash = ggplot() + geom_point(data=wash_smry, aes(y=wash_mean, x=condition, color = condition), size = 3) +geom_errorbar(data=wash_smry, aes(y=wash_mean, x=condition, ymin = wash_mean - wash_se,ymax = wash_mean + wash_se, color = condition), size = 1, width = 0) + #geom_boxplot(data=washout, aes(y=wash, x=condition, color = condition), outlier.shape=NA) +
  scale_color_manual(values = custom_palette) +
  scale_fill_manual(values = custom_palette) +
  ylab("Washout Retention (%)") +
  xlab("Condition") +
  ylim(0,1.1)+
  theme(legend.position="none")
plot_wash

write.csv(wash_smry,"output_fig1PanelI_wash_meanSEM.csv", row.names = TRUE)
```


```{r}
ggarrange(plot_lcs,
          ggarrange(plot_lr, plot_asym, plot_delasym, plot_wash, ncol=4, legend=NULL),
          nrow = 2, common.legend = T)
```